const services = [
  ["accurate", "通用文字识别（高精度含位置版）", "通用文字", "ocr/v1/accurate", "500"],
  ["accurate_basic", "通用文字识别（高精度版）", "通用文字", "ocr/v1/accurate_basic", "997"],
  ["general", "通用文字识别（标准含位置版）", "通用文字", "ocr/v1/general", "1000"],
  ["general_basic", "通用文字识别（标准版）", "通用文字", "ocr/v1/general_basic", "1000"],
  ["webimage", "网络图片文字识别", "通用文字", "ocr/v1/webimage", "1000"],
  ["webimage_loc", "网络图片文字识别（含位置版）", "通用文字", "ocr/v1/webimage_loc", "500"],
  ["pp_ocrv5", "PPOCR-v6", "通用文字", "ocr/v1/pp_ocrv5", "1000"],
  ["general_ocr", "通用卡证票据识别", "通用文字", "ocr/v1/general_ocr", "200"],
  ["handwriting", "手写文字识别", "通用文字", "ocr/v1/handwriting", "500"],
  ["numbers", "数字识别", "通用文字", "ocr/v1/numbers", "1000"],
  ["formula", "公式识别", "通用文字", "ocr/v1/formula", "1000"],
  ["idcard", "身份证识别", "证件", "ocr/v1/idcard", "1000", { id_card_side: "front" }],
  ["bankcard", "银行卡识别", "证件", "ocr/v1/bankcard", "1000"],
  ["driving_license", "驾驶证识别", "证件", "ocr/v1/driving_license", "1000"],
  ["vehicle_license", "行驶证识别", "证件", "ocr/v1/vehicle_license", "1000"],
  ["license_plate", "车牌识别", "交通", "ocr/v1/license_plate", "1000"],
  ["passport", "护照识别", "证件", "ocr/v1/passport", "200"],
  ["overseas_passport", "海外护照识别", "证件", "ocr/v1/overseas_passport", "200"],
  ["household_register", "户口本识别", "证件", "ocr/v1/household_register", "200"],
  ["birth_certificate", "出生证明识别", "证件", "ocr/v1/birth_certificate", "200"],
  ["marriage_certificate", "结婚证识别", "证件", "ocr/v1/marriage_certificate", "200"],
  ["divorce_certificate", "离婚证识别", "证件", "ocr/v1/divorce_certificate", "200"],
  ["social_security_card", "社保卡识别", "证件", "ocr/v1/social_security_card", "200"],
  ["HK_Macau_exitentrypermit", "港澳通行证识别", "证件", "ocr/v1/HK_Macau_exitentrypermit", "200"],
  ["taiwan_exitentrypermit", "台湾通行证识别", "证件", "ocr/v1/taiwan_exitentrypermit", "200"],
  ["receipt", "通用票据识别", "票据", "ocr/v1/receipt", "1000"],
  ["invoice", "通用机打发票识别", "票据", "ocr/v1/invoice", "200"],
  ["vat_invoice", "增值税发票识别", "票据", "ocr/v1/vat_invoice", "1000"],
  ["quota_invoice", "定额发票识别", "票据", "ocr/v1/quota_invoice", "200"],
  ["vehicle_invoice", "机动车销售发票识别", "票据", "ocr/v1/vehicle_invoice", "200"],
  ["used_vehicle_invoice", "二手车销售发票识别", "票据", "ocr/v1/used_vehicle_invoice", "200"],
  ["taxi_receipt", "出租车票识别", "票据", "ocr/v1/taxi_receipt", "200"],
  ["toll_invoice", "过路过桥费发票识别", "票据", "ocr/v1/toll_invoice", "200"],
  ["shopping_receipt", "购物小票识别", "票据", "ocr/v1/shopping_receipt", "200"],
  ["business_license", "营业执照识别", "商业", "ocr/v1/business_license", "1000"],
  ["business_card", "名片识别", "商业", "ocr/v1/business_card", "500"],
  ["train_ticket", "火车票识别", "交通", "ocr/v1/train_ticket", "200"],
  ["air_ticket", "飞机行程单识别", "交通", "ocr/v1/air_ticket", "200"],
  ["bus_ticket", "汽车票识别", "交通", "ocr/v1/bus_ticket", "200"],
  ["ferry_ticket", "船票识别", "交通", "ocr/v1/ferry_ticket", "200"],
  ["vin_code", "VIN 码识别", "交通", "ocr/v1/vin_code", "200"],
  ["vehicle_certificate", "车辆合格证识别", "交通", "ocr/v1/vehicle_certificate", "200"],
  ["vehicle_registration_certificate", "机动车登记证书识别", "交通", "ocr/v1/vehicle_registration_certificate", "200"],
  ["road_transport_certificate", "道路运输证识别", "交通", "ocr/v1/road_transport_certificate", "200"],
  ["qrcode", "二维码识别", "场景文字", "ocr/v1/qrcode", "500"],
  ["facade", "门脸文字识别", "场景文字", "ocr/v1/facade", "500"],
  ["meter", "仪器仪表盘读数识别", "场景文字", "ocr/v1/meter", "500"],
  ["seal", "印章识别", "场景文字", "ocr/v1/seal", "500"],
  ["waybill", "快递面单识别", "场景文字", "ocr/v1/waybill", "200"],
  ["weight_note", "磅单识别", "场景文字", "ocr/v1/weight_note", "200"],
  ["pen", "词典笔文字识别", "场景文字", "ocr/v1/pen", "500"],
  ["table", "表格文字识别 V2", "文档", "ocr/v1/table", "500"],
  ["doc_analysis", "试卷分析与识别", "文档", "ocr/v1/doc_analysis", "500"],
  ["doc_analysis_office", "办公文档识别", "文档", "ocr/v1/doc_analysis_office", "500"],
  ["doc_classify", "文件检测分类", "文档", "ocr/v1/doc_classify", "200"],
  ["smart_struct", "智能结构化", "文档", "ocr/v1/smart_struct", "200"],
  ["medical_record", "病案首页识别", "医疗", "ocr/v1/medical_record", "200"],
  ["medical_statement", "医疗费用结算单识别", "医疗", "ocr/v1/medical_statement", "200"],
  ["medical_invoice", "医疗发票识别", "医疗", "ocr/v1/medical_invoice", "200"],
  ["medical_detail", "医疗费用明细识别", "医疗", "ocr/v1/medical_detail", "200"],
  ["medical_report_detection", "医疗检验报告单识别", "医疗", "ocr/v1/medical_report_detection", "200"],
  ["medical_summary", "出院小结识别", "医疗", "ocr/v1/medical_summary", "200"],
  ["health_report", "诊断报告单识别", "医疗", "ocr/v1/health_report", "200"]
];

export const OCR_SERVICES = services.map(([id, name, category, path, freeQuota, params = {}]) => ({ id, name, category, path, freeQuota, params }));

export function findOcrService(id) {
  return OCR_SERVICES.find((service) => service.id === id);
}

export function publicOcrServices() {
  return OCR_SERVICES.map(({ id, name, category, freeQuota }) => ({ id, name, category, freeQuota }));
}
